### ISSUE TITLE
get the episodes of a show for a Specific Season

### ISSUE THREAD

**Issue by jlexige** [HristoKolev/TvDbSharper#17]
Hi,

Instead of get all the episoed for a show and then test the season number, could you give me an example of the code with TvDbSharper  to have the "?airedSeason=" of the API (/series/{id}/episodes/query).

Thanks

**Comment by HristoKolev** [comment]
Use this overload: https://github.com/HristoKolev/TvDbSharper/blob/master/src/TvDbSharper/Clients/SeriesClient.cs#L38
