### ISSUE TITLE
Search result missing Image field

### ISSUE THREAD

**Issue by jasondavis303** [HristoKolev/TvDbSharper#18]
On some series searches, the json returned has an "image" field, in addition to the banner, fanart and poster fields. The field isn't part of the deserialized json class.  When searching for "Selfie", the first data item looks like this:

{
      "aliases": [],
      "banner": null,
      "firstAired": "2014-8-19",
      "id": 279529,
      **"image": "/banners/posters/279529-2.jpg",**
      "network": "ABC (US)",
      "overview": "Eliza Dooley has 263,000 followers who hang on to her every post, tweet and selfie.   But one lonely day she has a revelation: being friended is not the same as having actual friends.  She asks marketing guru Henry to 'rebrand' her self-obsessed reputation and teach her how to connect.",
      "poster": null,
      "seriesName": "Selfie",
      "slug": "selfie",
      "status": "Ended"
    }

**Comment by HristoKolev** [comment]
I will look into it.

**Comment by HristoKolev** [comment]
Added in v3.1.0
