### ISSUE TITLE
How to know if Authenticate request was successful - client.Authentication.Token always returns null

### ISSUE THREAD

**Issue by rb0135** [HristoKolev/TvDbSharper#19]
Hi,

Just checking how to know the await client.Authentication.AuthenticateAsync(<apikey>) call is successful or not.

I presumed a call to client.Authentication.Token would return the token if successfull or null/error if not. I am always getting getting null.

However, when I tried to just test searching a Series after the AuthenticateAsync, I do get valid data back, so presuming the Authentication must have been successful.

So, this is the test code that I do get data back:

`
await client.Authentication.AuthenticateAsync(<apikey>);

var token = client.Authentication.Token; **<----- returns null**

var response = await client.Series.GetAsync(78804);
Debug.WriteLine(response.Data.SeriesName); // <-- returns Doctor Who (2005)
Debug.WriteLine(response.Data.Network); // <-- returns BBC One
Debug.WriteLine(response.Data.ImdbId); // <-- returns tt0436992
`

Just trying to put some error trapping smarts into my program.
Rob

**Comment by Jonathan-Jackson** [comment]
Hi Rob,

I can't speak for the lib author, but in my case the token is not null after authenticating:

![image](https://user-images.githubusercontent.com/53373436/82327751-c2e41500-99d6-11ea-9bf7-e6c3dfae2a92.png)

That said, I am passing the ApiKey through the authentication - how are you doing this? The version I am running on does not accept zero arguments.

Jon.

**Comment by HristoKolev** [comment]
Welcome @rb0135 , can you please give me a complete executable example (minus your login details).

I want to see which `AuthenticateAsync` you are calling. 

Also, I would like to know the version of the library you are using and the runtime and it's version.

If auth fails, an exception should be thrown, otherwise you should get a valid auth token.

**Comment by rb0135** [comment]
Thanks @Jonathan-Jackson and @HristoKolev.

Further to my question, I could only get the call to work once, now when it trys to run this line, it takes me straight out of the routine. await client.Authentication.AuthenticateAsync(<apikey>);

There is no error, I tried to put a try/catch around the code just in case and that didnt even trigger.

Im using the Authentication.AuthenticateAsync("api key") overload. It seems TVDB only need the API key with there V3 as my UserKey from them is blank. They said I didnt need it now.

I have tested on their API webpage (https://api.thetvdb.com/swagger#!) with just the API key in their examples and it works fine each time.

So, here is the code I am trying:

` public async Task InitialiseTVDB()
{
ITvDbClient clienttvdb = new TvDbClient()
await clienttvdb.Authentication.AuthenticateAsync("my api key"); **<-- has a brief pause then totally exists the routine**

var response = await clienttvdb.Series.GetAsync(78804);  **<-- Never gets here. It did once, even though Tokin was null**

Console.WriteLine(response.Data.SeriesName); //Doctor Who (2005)
Console.WriteLine(response.Data.Network); //BBC One
Console.WriteLine(response.Data.ImdbId); //tt0436992`
}

Thanks again for your help.

Much appreciated.
Rob

**Comment by rb0135** [comment]
Just an update.

I did some more testing today and solved 1 problem.
Solved:
Where calling the AuthenticateAsync and it dropped straight out - cause by missing an await in front of a calling routine (DOH).

However, I have found that client.Authenticate.Token does report a Token sometime, but other time null, however, even when it is reported the token is null, I can still query the API and get results.

So, it seems internally to tvdbsharper, it knows it has a valid token from the authenticate request. 

Not sure why I get null a lot of times.

Thanks, Rob

**Comment by rb0135** [comment]
Hi,

Ive made some progress where I get a Tokin recorded in client.Authenticate.Token every time.

Within my project (I had already done this but decided to do it again), was to remove the tvdbsharper package from the solution (through NuGet), did a clean solution command, then re-installed the package (again through NuGet) and now it seems OK.

Honestly, is it a coincidence?
