### ISSUE TITLE
Passing a title with a semicolon to Search by Name results in Method Not Allowed

### ISSUE THREAD

**Issue by da3dsoul** [HristoKolev/TvDbSharper#2]
The example I found was Chaos;Head.
With char.ToLower(), I could also see it handling some languages (German) poorly, as they have a non-binary case for some letters.

I would recommend using UrlEncode on the search parameter. I would recommend keeping case instead of using ToLower (just in case), unless TvDB has a rule or poor coding for it.

**Comment by HristoKolev** [comment]
Thank you for taking your time to report this.

Url encoding seems to work. It's interesting, I have to see how many other places need that too.

I thing that  `char.ToLower()` is not used on user passed values. Have to look into it later.

**Comment by da3dsoul** [comment]
No problem and thanks for the work. It isn't a difficult thing to write, but it's tedious to debug, so I've no doubt you've put many hours into it.

**Comment by HristoKolev** [comment]
The only place that needed url encoding was the search client. I haven't thought about this... it's the only place that takes user input...

The lower case stuff doesn't apply to user input and can't break anything.

I updated the package.
------

I just saw that you are actually using this package in one of your projects... :)

If you find any more bugs or have any suggestions, please let me know. :)

**Comment by da3dsoul** [comment]
Cool thanks
