### ISSUE TITLE
ImageType can be bull

### ISSUE THREAD

**Issue by StephenDMorris** [HristoKolev/TvDbSharper#26]
I think that ImageType  in TvDBClient.Generated.cs should be nullable on lines 1203 and 1272, the base and extended EpisodeDTO
![Screenshot 2021-12-09 192358](https://user-images.githubusercontent.com/28726011/145529943-f152f3e7-cabd-41f9-8e8f-7423efed59a4.jpg)
.

**Comment by HristoKolev** [comment]
I'll look at it this evening.

**Comment by StephenDMorris** [comment]
Cool, thank you. Was just looking out how to create a PR. Would you like me to do that or just leave it with you?

**Comment by HristoKolev** [comment]
Leave it to me, that file is generated and it would take more than just changing it to fix the issue.

**Comment by HristoKolev** [comment]
Fixed in v4.0.2
