### ISSUE TITLE
"translations" is missing using "/movies/{id}/extended"

### ISSUE THREAD

**Issue by DanCooper** [HristoKolev/TvDbSharper#29]
... or **maybe** it's missing, because in the API documentation it's not listed under "200 - result" schema, but if you execute the swagger it's in the result (see https://pastebin.com/WP5tjUcA).

So I'm not shure if this is an issue in the documentation or in the result. But that would save an additional API call, since you wouldn't have to call up the translations (/movies/{id}/translations/{language}).

**Comment by DanCooper** [comment]
I have to correct what I said a bit: "translations" is only included if the parameter "meta=translations" is used (e.g. "https://api4.thetvdb.com/v4/movies/165/extended?meta=translations"). Nevertheless it is missing in the "MovieExtendedRecordDto".

**Comment by HristoKolev** [comment]
Hi again,

It's not even about the swagger being incomplete, there are many, MANY places where it's just wrong. I have an entire separate application built specifically to deal with that. This is not their first time building a bad API, I've been working with their data for 7 years now and with each iteration if the API they remove some problems are add some more.

If you keep reporting these cases and provide me with the method that you called and it's parameters I'll be happy to fix them.

I'll look at this tomorrow as I was about to sign off for today.

**Comment by DanCooper** [comment]
I know... :)

I'm working with TVDb in Ember Media Manager since 10 years and still use the v2 API because off all the issues with the new ones. But I think it's time to switch to the new one (we all know why) and I'm happy that someone else writes a wrapper, hehe ;-)

I will continue to report all issues and thank you in advance for your work! I'm also off for tonight.

**Comment by HristoKolev** [comment]
Fixed in v4.0.7.
