### ISSUE TITLE
Null error in PeopleExtended

### ISSUE THREAD

**Issue by WilliamrK305** [HristoKolev/TvDbSharper#31]
I get this error for Gender when it's not entered it returns null instead of an integer.
Error converting value {null} to type 'System.Int32'. Path 'data.gender', line 1, position 264.

**Comment by HristoKolev** [comment]
Hi, can you provide me with the exact call you made? The method and the parameters.

**Comment by WilliamrK305** [comment]
PeopleId = (Convert.ToInt32(((CastMembers)e.ClickedItem).PeopleID));
            CastInformation("PeopleExtended(379858)", await client.PeopleExtended(PeopleId, new PeopleExtendedOptionalParams { Meta = "translations" }));

	private async void CastInformation(string tag, object obj)
        {
            CastCreditsCollection.Clear();
            CastCreditsList.ItemsSource = null;
            JsonConvert.SerializeObject(obj, Formatting.Indented);
            int endcount = ((TvDbSharper.TvDbApiResponse<TvDbSharper.PeopleExtendedRecordDto>)obj).Data.Characters.Length;
            //for (int i = 0; i < endcount; i++)
            //{
            string birth = ((TvDbSharper.TvDbApiResponse<TvDbSharper.PeopleExtendedRecordDto>)obj).Data.Birth;
            string death = ((TvDbSharper.TvDbApiResponse<TvDbSharper.PeopleExtendedRecordDto>)obj).Data.Death;
            long id = ((TvDbSharper.TvDbApiResponse<TvDbSharper.PeopleExtendedRecordDto>)obj).Data.Id;
            string image = ((TvDbSharper.TvDbApiResponse<TvDbSharper.PeopleExtendedRecordDto>)obj).Data.Image;
            gender = Convert.ToInt32(((TvDbSharper.TvDbApiResponse<TvDbSharper.PeopleExtendedRecordDto>)obj).Data.Gender);
            string birthplace = ((TvDbSharper.TvDbApiResponse<TvDbSharper.PeopleExtendedRecordDto>)obj).Data.BirthPlace;
            
            CastInfo result = new CastInfo()
            {
                Id = id,
                Birth = birth,
                Death = death,
                Image = image,
                Birthplace = birthplace,
                Gender = gender
            };
            CastCreditsCollection.Add(result);
            CastCreditsList.ItemsSource = CastCreditsCollection;
            //}
        }

This works as long as the gender is actually set in thetvdb.com database but if it's left blank it fails on gender.

**Comment by HristoKolev** [comment]
Thank you, I'll release a new version in a 3 hours.

**Comment by HristoKolev** [comment]
Fixed in v4.0.10.

**Comment by WilliamrK305** [comment]
Thanks for the quick fix.
Works perfectly now.
