### ISSUE TITLE
SearchSeriesResult doesn't have a Language tag?

### ISSUE THREAD

**Issue by da3dsoul** [HristoKolev/TvDbSharper#6]
This may be on the fault of the API. I'll admit I haven't looked. The xml api had Language tags for search results. SearchSeriesResult doesn't have it. Is it assumed "en"? The are situations where you get not English results due to foreign releases. Disney is plagued with that, Studio Ghibli anime (Spirited Away, Castle in the Sky, etc) as well.

**Comment by HristoKolev** [comment]
This is what the API returns:
```
{
  "aliases": [
    "string"
  ],
  "banner": "string",
  "firstAired": "string",
  "id": 0,
  "network": "string",
  "overview": "string",
  "seriesName": "string",
  "status": "string"
}
```
https://api.thetvdb.com/swagger#!/Search/get_search_series

**Comment by da3dsoul** [comment]
I see. You pass language as a header, and then everything returned will only be of that language.

**Comment by HristoKolev** [comment]
Yes. You set `de` to the `AcceptedLanguage` property of the client and you get things in German.

**Comment by da3dsoul** [comment]
You have the language handled properly in the Client as well. Thanks, and closing.
