### ISSUE TITLE
'Content-Type' header error

### ISSUE THREAD

**Issue by acosano** [HristoKolev/TvDbSharper#8]
Hi I'm keep getting the fallowing error when I try to login.

The 'Content-Type' header must be modified using the appropriate property or method.
Parameter name: name

Any help is appreciated.

Cheers

**Comment by HristoKolev** [comment]
Rollback for now, I'll fix this ASAP.

**Comment by HristoKolev** [comment]
Fixed in new version of the package.

**Comment by acosano** [comment]
Thanks for the quick fix.

Still fighting with the login as I don't get any response  back using 
`await client.Authentication.AuthenticateAsync("ApiKey");
Or
`await client.Authentication.AuthenticateAsync("ApiKey", "Username", "UserKey");`

I don't believe it has anything to do with your library; more with the TVDB server and the new API.

As much I love TVDB, I'm almost about to give up and move to TvMaze. I never encounter so many problem with the old API only with the new one.

**Comment by HristoKolev** [comment]
I get it, the new api is a anorexic, but ti's not so bad.

Try to create a new project and reproduce your issue, if you can do that, maybe I can help you.

**Comment by acosano** [comment]
Try it on new project and when I was about to close it finally I got feedback.

Took almost 3 min. and 5 System.Net.Sockets.SocketException to get authenticated.
After that all other request are super fast.

You have no idea how much this means for me to get this to work as my program stop working and I have to take the download link off until I can move all to the new API. I even starting it from scratch using Devexpress Components. you can see the old version here [http://gygasoft.com](url)

Thanks your help, very much appreciated.

**Comment by HristoKolev** [comment]
So, they dropped the old API?

**Comment by acosano** [comment]
Looks like as I can't get any thing with the old API.

I hope there sort the Authentication as 3 min. is a bit long.

**Comment by HristoKolev** [comment]
Try to install this version of the package and tell me if you get the issue,

https://www.nuget.org/packages/TvDbSharper/0.6.3

**Comment by acosano** [comment]
That one is given me this error.

`System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.`

**Comment by HristoKolev** [comment]
What platform are you using ?

**Comment by acosano** [comment]
Can't it be that I have compile your source for Framework 4.5.2 from the source instead of using the package?

**Comment by acosano** [comment]
I'm on windows 10 Pro, Running Visual Studio Enterprise 2017.

**Comment by HristoKolev** [comment]
This shouldn't be the case. There is a reason why we use Nuget.


Do you handle the async stuff properly?

**Comment by HristoKolev** [comment]
Can you run this code and see what happens? 
```

namespace ConsoleApp2
{
    using System;
    using System.Threading.Tasks;

    using TvDbSharper;

    public class EntryPint
    {
        public static void Main(string[] args) => new EntryPint().MainAsync(args).GetAwaiter().GetResult();

        public async Task MainAsync(string[] args)
        {
            var client = new TvDbClient();

            await client.Authentication.AuthenticateAsync("xxxxx");

            var response = await client.Series.GetAsync(78804);

            // Console.WriteLine(string.Join(", ", response.Data.Favorites.Select(s => s)));
            Console.WriteLine(response.Data.SeriesName); // Doctor Who (2005)
            Console.WriteLine(response.Data.Network); // BBC One
            Console.WriteLine(response.Data.ImdbId); // tt0436992
        }
    }
}
```

**Comment by acosano** [comment]
I fallow your sample code on the site for testing. But I have to admit I using VB.

Still the same I'm starting to believe that something is wrong with my computer and I will rebuild it tomorrow. I will keep you posted.

Imports TvDbSharper
Imports System.Threading.Tasks
Imports System

```
Namespace ConsoleApp2

	Public Class EntryPint
		Public Shared Sub Main(ByVal args() As String)
			Call (New EntryPint()).MainAsync(args).GetAwaiter().GetResult()
		End Sub

		Public Async Function MainAsync(ByVal args() As String) As Task
			Dim client = New TvDbClient()

			Await client.Authentication.AuthenticateAsync("xxxxx")

			Dim response = Await client.Series.GetAsync(78804)

			' Console.WriteLine(string.Join(", ", response.Data.Favorites.Select(s => s)));
			Console.WriteLine(response.Data.SeriesName) ' Doctor Who (2005)
			Console.WriteLine(response.Data.Network) ' BBC One
			Console.WriteLine(response.Data.ImdbId) ' tt0436992

		End Function

	End Class

End Namespace
```

**Comment by acosano** [comment]
I try it this morning (6 am) at  work and is working fine. So it must be my computer at hoe that is given the headache. Will rebuild it later and hopefully everything works fine and  I can work on the new app.

Thank you very much for your help.

**Comment by HristoKolev** [comment]
You may have some kind of network issue. 3 minuets per request is way too much.

I'm happy that things turned out OK for you.

If you have any problems in the future, don't hesitate to open an issue.
