### ISSUE TITLE
Need some help.

### ISSUE THREAD

**Issue by acosano** [HristoKolev/TvDbSharper#9]
Hi m8,

I finally got all working after I reset the computer. 

I like to ask you if you could give me a hint on how to get the images as I have try a lot but I'm just not able to get images. I struggle mostly with the query part as I could not find any information on the parameters.

Any hint is appreciated.

**Comment by HristoKolev** [comment]
Here is the API docs on that endpoint: https://api.thetvdb.com/swagger#!/Series/get_series_id_images_query

Here is the image query class: 
https://github.com/HristoKolev/TvDbSharper/blob/master/src/TvDbSharper/Dto/SeriesDtos.cs#L96

The keyType is an enum for the kind of image you want... fanart, poster, etc.
